###
POST http://localhost:8080/api/inventoryitems/save
Content-Type: application/json
Accept: application/json

{
  "inventoryId": "ABC123",
  "itemType": "HIGH_VALUE_ASSET",
  "name": "laptop",
  "amount": 1
}

###
POST http://localhost:8080/api/inventoryitems/save
Content-Type: application/json
Accept: application/json

{
  "inventoryId": "FGT576",
  "itemType": "HIGH_VALUE_ASSET",
  "name": "binoculars",
  "description": "KOWA Genesis 10.5*44",
  "amount": 2,
  "responsibleType": "EMPLOYEE",
  "responsibleId": 103
}

###
POST http://localhost:8080/api/inventoryitems/saveAll
Content-Type: application/json
Accept: application/json

[
  {
    "inventoryId": "ABX5/FG",
    "itemType": "HIGH_VALUE_ASSET",
    "name": "desktop pc",
    "description": "HP Workstation",
    "amount": 2,
    "responsibleType": "DEPARTMENT",
    "responsibleId": 14
  },
  {
    "inventoryId": "ZGF458",
    "itemType": "LOW_VALUE_ASSET",
    "name": "pendrive",
    "amount": 20,
    "responsibleType": "DEPARTMENT",
    "responsibleId": 12
  }
]

###
GET http://localhost:8080/api/inventoryitems
Accept: application/json

###
GET http://localhost:8080/api/inventoryitems/?substringOfName=nocul
Accept: application/json

###
GET http://localhost:8080/api/inventoryitems/findByInventoryId/ZGF458
Accept: application/json

###
PUT http://localhost:8080/api/inventoryitems/update/1
Content-Type: application/json
Accept: application/json

{
  "description": "HP VivoBook",
  "serialNumber": "HGF789DEF"
}

###
PUT http://localhost:8080/api/inventoryitems/update/1
Content-Type: application/json
Accept: application/json

{
  "description": "MacBook Pro",
  "serialNumber": "BGH569HT",
  "name": "Macbook"
}

###
DELETE http://localhost:8080/api/inventoryitems/delete/1
Accept: application/json