version: '3.9'

name: "inventory"

services:
  inventory-database:
    image: postgres:14.3-alpine
    container_name: inventory_db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

  inventory-app:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    image: ferencattila/inventory
    container_name: inventory_app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-database:5432/inventory
      SPRING_DATASOURCE_USER: inventory
      SPRING_DATASOURCE_PASSWORD: inventory
    depends_on:
      - inventory-database
