version: '3.9'
services:
  database:
    image: postgres:14.2-alpine
    container_name: inventory_db
    restart: on-failure
    ports:
      - '5432:5432'
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    image: inventory
    container_name: inventory_app
    restart: on-failure
    depends_on:
      - database

