version: '3.9'

services:
  inventory-dev-database:
    image: postgres:14.4-alpine
    container_name: inventory_dev_db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./init-inventory-db.sh:/docker-entrypoint-initdb.d/init-inventory-db.sh
      - ./db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

  inventory-test-database:
    image: postgres:14.4-alpine
    container_name: inventory_test_db
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - ./init-inventory-db.sh:/docker-entrypoint-initdb.d/init-inventory-db.sh
      - ./test-db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

  keycloak:
    image: bitnami/keycloak:19
    container_name: keycloak
    restart: on-failure
    ports:
      - "8081:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: root
      KEYCLOAK_ADMIN_PASSWORD: root
#      DB_VENDOR: postgres
      KEYCLOAK_DATABASE_HOST: inventory-dev-database
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_PRODUCTION: false
# In production use, you must set KEYCLOAK_PRODUCTION to true, and you have to also configure the following variables:
#     KEYCLOAK_ENABLE_TLS: true
#     Add following values as files to the container:
#     KEYCLOAK_TLS_KEYSTORE_FILE: /opt/bitnami/keycloak/certs/keystore.jks
#     KEYCLOAK_TLS_TRUSTSTORE_FILE: /opt/bitnami/keycloak/certs/truststore.jks
#     KEYCLOAK_TLS_KEYSTORE_PASSWORD: someSecurePassword
#     KEYCLOAK_TLS_TRUSTSTORE_PASSWORD: someSecurePassword
    depends_on:
      - inventory-dev-database

  inventory-app:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    image: ferencattila/inventory
    container_name: inventory_app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-dev-database:5432/inventory
      SPRING_DATASOURCE_USER: inventory
      SPRING_DATASOURCE_PASSWORD: inventory
    depends_on:
      - inventory-dev-database
      - keycloak
    entrypoint: ['/opt/bin/wait-for-it.sh', '-t', '120', 'inventory-dev-database:5432', '--', 'java', 'org.springframework.boot.loader.JarLauncher']
