version: '3.9'

services:
  inventory-dev-database:
    image: postgres:14.4-alpine
    container_name: inventory_dev_db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./init-inventory-db.sh:/docker-entrypoint-initdb.d/init-inventory-db.sh
      - ./db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

  inventory-test-database:
    image: postgres:14.4-alpine
    container_name: inventory_test_db
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - ./init-inventory-db.sh:/docker-entrypoint-initdb.d/init-inventory-db.sh
      - ./test-db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      DB_VENDOR: postgres
      DB_ADDR: inventory-dev-database
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    depends_on:
      - inventory-dev-database

  inventory-app:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    image: ferencattila/inventory
    container_name: inventory_app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-dev-database:5432/inventory
      SPRING_DATASOURCE_USER: inventory
      SPRING_DATASOURCE_PASSWORD: inventory
    depends_on:
      - inventory-dev-database
      - keycloak
    entrypoint: ['/opt/bin/wait-for-it.sh', '-t', '120', 'inventory-dev-database:5432', '--', 'java', 'org.springframework.boot.loader.JarLauncher']
