CREATE TABLE departments
(
    id        BIGINT NOT NULL,
    leader_id BIGINT NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id    BIGINT        NOT NULL,
    email VARCHAR(150)  NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            date                                    NOT NULL,
    note_number     VARCHAR(50),
    event_type      VARCHAR(11)                             NOT NULL,
    description     TEXT,
    old_responsible BIGINT,
    new_responsible BIGINT,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE inventory_items
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inventory_id     VARCHAR(50)                             NOT NULL,
    item_type        VARCHAR(16)                             NOT NULL,
    name             VARCHAR(100)                            NOT NULL,
    description      TEXT,
    serial_number    VARCHAR(100),
    start_unit_price DOUBLE PRECISION                        NOT NULL,
    responsible_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_inventory_items PRIMARY KEY (id)
);

CREATE TABLE inventory_items_events
(
    event_id          BIGINT NOT NULL,
    inventory_item_id BIGINT NOT NULL
);

CREATE TABLE responsible
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(150)                            NOT NULL,
    CONSTRAINT pk_responsible PRIMARY KEY (id)
);

ALTER TABLE departments
    ADD CONSTRAINT FK_DEPARTMENTS_ON_ID FOREIGN KEY (id) REFERENCES responsible (id);

ALTER TABLE departments
    ADD CONSTRAINT FK_DEPARTMENTS_ON_LEADER FOREIGN KEY (leader_id) REFERENCES employees (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_ID FOREIGN KEY (id) REFERENCES responsible (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_NEW_RESPONSIBLE FOREIGN KEY (new_responsible) REFERENCES responsible (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_OLD_RESPONSIBLE FOREIGN KEY (old_responsible) REFERENCES responsible (id);

ALTER TABLE inventory_items
    ADD CONSTRAINT FK_INVENTORY_ITEMS_ON_RESPONSIBLE FOREIGN KEY (responsible_id) REFERENCES responsible (id);

ALTER TABLE inventory_items_events
    ADD CONSTRAINT fk_inviteeve_on_event FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE inventory_items_events
    ADD CONSTRAINT fk_inviteeve_on_inventory_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id);