DROP TABLE users_roles;
DROP TABLE roles;
DROP TABLE users;

CREATE TABLE permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   description VARCHAR(255),
   CONSTRAINT pk_permissions PRIMARY KEY (id)
);


CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255),
   password VARCHAR(255),
   email VARCHAR(255),
   is_account_non_expired BOOLEAN NOT NULL,
   is_account_non_locked BOOLEAN NOT NULL,
   is_credentials_non_expired BOOLEAN NOT NULL,
   is_account_enabled BOOLEAN NOT NULL,
   CONSTRAINT pk_users PRIMARY KEY (id)
);


CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE roles_permissions (
  permission_id BIGINT NOT NULL,
   role_id BIGINT NOT NULL,
   CONSTRAINT pk_roles_permissions PRIMARY KEY (permission_id, role_id)
);

ALTER TABLE roles_permissions ADD CONSTRAINT fk_rolper_on_inventory_user_permission FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE roles_permissions ADD CONSTRAINT fk_rolper_on_inventory_user_roles FOREIGN KEY (role_id) REFERENCES roles (id);

CREATE TABLE user_roles (
  role_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL,
   CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

ALTER TABLE user_roles ADD CONSTRAINT fk_userol_on_inventory_user_roles FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);