ALTER TABLE permissions ALTER COLUMN description TYPE TEXT USING (description::TEXT);

CREATE TABLE settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255)                          NOT NULL,
  value INT                                  NOT NULL,
  CONSTRAINT pk_settings PRIMARY KEY (id)
);

INSERT INTO settings (name, value) values ('default_user_is_set', 0);